[librealsense]Update the README.md file
01org/node-realsense pull request #179
Opened 2017-03-27 07:44 UTC by minggangw

To align the format of README.md with other modules' README.

2017-03-27 07:45 UTC, minggangw commented
@kenny-y PTAL, thanks!

2017-03-29 07:09 UTC, kenny-y requested changes

2017-03-29 07:09 UTC, kenny-y commented on src/librealsense/README.md
> +  device.enableStream('color', mode).then(() => {
Better to have depth stream to directly demonstrate the ability of RealSense camera

2017-03-29 07:09 UTC, kenny-y commented on src/librealsense/README.md
> +- [Concept and terms](https://software.intel.com/sites/products/realsense/person/developer_guide.html#Introduction)
A link to https://github.com/IntelRealSense/librealsense is recommended, PersonTracking link seems no use here...

2017-03-29 07:09 UTC, kenny-y commented on src/librealsense/README.md
> +  device.context = context;
I think we should find a good way to workaround the GC issue, and also make the code prettier than this :)

2017-03-30 05:54 UTC, kenny-y approved these changes

2017-03-30 05:55 UTC, merged